import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="NextJs, Coding Hunter, Abdul Muid" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script></Script>
      
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.heroSection}>
            <h1 className={styles.title}>Hunting Coder</h1>
            <img
              className={styles.image}
              src="/images/home.jpg"
              width={237}
              height={158}
              alt="hunting coder"
            />
          </div>

          <p className={styles.tagline}>A blog for the hunting coder by a hunting coder</p>
          
          <div className={styles.blogContainer}>
            <h2 className={styles.blogHeading}>Latest Blog</h2>
            
            <div className={styles.blogItem}>
              <h3 className={styles.blogTitle}>Hunting Code</h3>
              <p className={styles.blogDescription}>A blog for hunting coders by a hunting coder</p>
            </div>

            <div className={styles.blogItem}>
              <h3 className={styles.blogTitle}>Hunting Code</h3>
              <p className={styles.blogDescription}>A blog for hunting coders by a hunting coder</p>
            </div>

            <div className={styles.blogItem}>
              <h3 className={styles.blogTitle}>Hunting Code</h3>
              <p className={styles.blogDescription}>A blog for hunting coders by a hunting coder</p>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
